# Generated by Django 5.0.1 on 2024-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posthashtags",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
