# Generated by Django 5.0.1 on 2024-01-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_remove_posthashtags_post_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
