# Generated by Django 5.0.1 on 2024-01-05 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="email",
        ),
    ]
