# Generated by Django 5.0.1 on 2024-01-05 14:34

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_user_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=user.models.user_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
