# Generated by Django 5.0.1 on 2024-01-07 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_userfollowing_following_user_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["id"], "verbose_name_plural": "profiles"},
        ),
    ]
