# Generated by Django 5.0.1 on 2024-01-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_userprofile_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollowing",
            name="unique_followers",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="user_id",
            new_name="you_follow_to",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="following_user_id",
            new_name="your_followers",
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                fields=("you_follow_to", "your_followers"), name="unique_followers"
            ),
        ),
    ]
