# Generated by Django 5.0.1 on 2024-01-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_remove_userfollowing_unique_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowing",
            name="you_follow_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="user.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userfollowing",
            name="your_followers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="user.userprofile",
            ),
        ),
    ]
